# Generated by Django 3.1.2 on 2020-10-06 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='articl_title',
            new_name='article_title',
        ),
    ]
